### ISSUE TITLE
How to get the parent link?

### ISSUE THREAD

**Issue by xpbliss** [xperimental/linky#1]
when get a url,  how to get the parent link o the url?

**Comment by xperimental** [comment]
I don't unterstand what you want to do. Could you be a bit more specific?

**Comment by xpbliss** [comment]
Oh , I want to know the dead or wrong url come from which url?  and the wrong url's href text?

**Comment by xperimental** [comment]
Currently this is not stored anywhere, but I plan to extend the data structure a bit. I'll keep your suggestion in mind.

**Comment by xperimental** [comment]
@xpbliss Can you check if what I added for [version 0.2.0](https://github.com/xperimental/linky/releases/tag/v0.2.0) is what you were looking for?
